import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

const Discover = () => {
  const router = useRouter();

  useEffect(() => {
    router.push({
      pathname: "./discover/overview",
      query: { headerCurrentLink: "overview" },
    });
  }, [router]);

  return (
    <>
      <Head>
        <title>Discover Web 3</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
    </>
  );
};

export default Discover;
