import Head from "next/head";
import styles from "../../../styles/discover.module.scss";
import { AppLayout } from "@/components/AppLayout";
import { useRouter } from "next/router";
import { useEffect } from "react";

const Discover = () => {
  const router = useRouter();

  useEffect(() => {
    router.push({
      pathname: "./discover/overview",
      query: { headerCurrentLink: "overview" },
    });
  }, [router]);

  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <></>
      </AppLayout>
    </>
  );
};

export default Discover;
