import Head from "next/head";

const Analytics = () => {
  return (
    <>
      <Head>
        <title>Analytics</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>

      <h1>Analytics</h1>
    </>
  );
};

export default Analytics;
