import Head from "next/head";

const Dashboard = () => {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>

      <h1>Dashboard</h1>

    </>
  );
};

export default Dashboard;
