import Head from "next/head";
const Ecosystem = () => {
  return (
    <>
      <Head>
        <title>Ecosystem</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <h1>Ecosystem</h1>

    </>
  );
};

export default Ecosystem;
