import { GetServerSideProps } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

const Home = () => {
  const router = useRouter();

  useEffect(() => {
    router.push("app/nodes");
  }, [router]);

  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Home;

export const getInitialProps: GetServerSideProps = async () => {
  // fetch user specific data from BE
  const userData = {
    userAva: "",
    userName: "",
    userEmail: "",
  };
  return {
    props: {
      userData,
    },
  };
};
