import Head from "next/head";
import { useRouter } from "next/router";
import { AppLayout } from "@/components/AppLayout";
import { useEffect } from "react";

const Home = () => {
  const router = useRouter();

  useEffect(() => {
    router.push("app/nodes");
  }, [router]);

  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout />
    </>
  );
};

export default Home;
