import Head from "next/head";

const Nodes = () => {
  return (
    <>
      <Head>
        <title>Nodes</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>

      <h1>Nodes</h1>

    </>
  );
};

export default Nodes;
