import Head from "next/head";
import { AppLayout } from "@/components/AppLayout";

const Teams = () => {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        {
          <main>
            <section>
              <h1>Teams</h1>
            </section>
          </main>
        }
      </AppLayout>
    </>
  );
};

export default Teams;
