import Head from "next/head";
import { AppLayout } from "@/components/AppLayout";

const Teams = () => {
  return (
    <>
      <Head>
        <title>Teams</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <h1>Teams</h1>
    </>
  );
};

export default Teams;
